### ISSUE TITLE
The latest version doesn't work.

### ISSUE THREAD

**Issue by aporiadin** [CultureHQ/polyfill-lambda#12]
There are 2 errors:
1) `Records: [{ cf: { request } }]` - Records is undefined
```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
at getUserAgent (/var/task/handler.js:6:25)
at handle (/var/task/handler.js:12:28)
```

2) `malformed Lambda proxy response` errors (502 status code)
doesn’t work with this header format:
```
headers: {
    "access-control-allow-origin": [{
      key: "Access-Control-Allow-Origin",
      value: "*"
    }],
    "content-type": [{
      key: "Content-Type",
      value: "application/javascript;charset=utf-8"
    }],
    "content-length": [{
      key: "Content-Length",
      value: polyfill.length
    }],
    "cache-control": [{
      key: "Cache-Control",
      value: cache ? "max-age=31536000" : null
    }]
},
```
works fine with:
```
headers: {
    "Access-Control-Allow-Origin": "*",
    "Content-Type": "application/javascript;charset=utf-8",
    "Content-Length": polyfill.length,
    "Cache-Control": cache ? "max-age=31536000" : null
},
```

**Comment by kddeisz** [comment]
Yeah. At the time that I deployed this a while ago I didn't have the lambda proxy integration set up. Now that I do it's not working. Just updated it on master since I needed to redeploy today to get a new runtime. Should be good now.
